# This is a basic workflow to help you get started with Actions

name: Polymer Build / FTP Deploy
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Utils & Bower Packages
        run: npm install
      - name: Build App with Vulcanize
        run: npm run build-polymer
      - name: FTP deploy www folder
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PWD }}
          local-dir: build/
          server-dir: /misc/
          log-level: verbose
          exclude: dev.html
            - build.html
            - vulcanized.html
            - bower_components
            - bower_components/**
            - bower_components/**/*